# Generated by Django 2.2 on 2019-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Enter the slug for this instance. No spaces!', unique=True, verbose_name='Thing slug')),
                ('display_order', models.IntegerField(default='1', help_text='Enter an integer that dictates the display order. Smaller is higher up the order.', verbose_name='Display order')),
                ('span_width', models.IntegerField(default='1', help_text='Enter an integer that determines how many columns the thing covers.', verbose_name='Column span')),
                ('header', models.TextField(help_text='Provide a title for the thing.', max_length=200, verbose_name='Thing Title')),
                ('blurb', models.TextField(blank=True, help_text="Enter some descriptive blurb. HTML formatting is supported. Don't add a hyperlink.", verbose_name='Blurb')),
                ('url_type', models.CharField(choices=[('0', 'No URL'), ('1', 'Internal URL (uses slug)'), ('2', 'External URL (opens new tab)')], default='1', help_text='What type of URL (if any) for this thing?', max_length=1, verbose_name='URL Type')),
                ('external_url', models.URLField(blank=True, help_text='Enter an external URL for this thing. Note that this only applies if the URL type is set to external.', verbose_name='URL to external resource')),
                ('background', models.FileField(blank=True, help_text="Select an image for the thing's background.", upload_to='things/grid-backgrounds/', verbose_name='Background grid image')),
                ('background_colour', models.CharField(default='#0072C6', help_text='Enter a hex colour (including the hash) for the background colour of this thing.', max_length=7, verbose_name='Background colour')),
                ('text_colour', models.CharField(default='#FFFFFF', help_text='Enter a hex colour (including the hash) for the text colour of this thing.', max_length=7, verbose_name='Text colour')),
                ('darken_title_background_by', models.IntegerField(default='20', help_text='Enter a value between 0 and 100 to darken the background colour of the header text by this percentage.', verbose_name='Darken title background colour (percentage)')),
                ('tags', models.TextField(blank=True, help_text='Enter markup for tags.', verbose_name='Tag markup')),
            ],
        ),
    ]
