# Generated by Django 2.2 on 2019-05-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='background_blurb',
            field=models.BooleanField(blank=True, default=False, help_text='Determines whether a background is applied to the text for the blurb. Can be used if background images are busy.', verbose_name='Apply background to blurb text?'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='url_type',
            field=models.CharField(choices=[('NO', 'No URL'), ('INT', 'Internal URL (uses slug)'), ('EXT', 'External URL (opens new tab)')], default='INT', help_text='What type of URL (if any) for this thing?', max_length=3, verbose_name='URL Type'),
        ),
    ]
